matrix:
  include:
    - language: dart
      dart:
        - "1.24.2"
    - language: node_js
      node_js:
        - "0.10"
    - language: rust
      script: 
        - cd rust/
        - cargo build --verbose --all
        - cargo test --verbose --all

# Define the list of directories to execute tests in.
env:
  - TEST_DIR=js
  - TEST_DIR=go
  - TEST_DIR=ruby
  - TEST_DIR=python
  - TEST_DIR=rust

# Test script to run. This is called once for each TEST_DIR value above.
script: ./run_tests.sh
