[package]
name = "olc"
description = "Library for translating between GPS coordinates (WGS84) and Open Location Code"
version = "0.1.0"
authors = ["James Fysh <james.fysh@gmail.com>"]
license = "MIT/Apache-2.0"
repository = "https://github.com/JamesFysh/open-location-code"
keywords = ["geography", "geospatial", "gis", "gps", "olc"]

[dependencies]
geo = "^0.4.3"
